kind = "DojoModel"
class_hash = "0x4a18279f4409ba81f2599dee8232c565ce08d084efff1d13007fd748621e5fb"
name = "nogame::fleet::models::active_mission_len"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "lenght"
type = "usize"
key = false
