kind = "DojoModel"
class_hash = "0x2bec9e62a9e8c73ad76ed185a4037a18d1c6fd1c64cbeb07af65d8da2e2c3f7"
name = "nogame::colony::models::colony_position"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "colony_id"
type = "u8"
key = true

[[members]]
name = "position"
type = "Position"
key = false
