kind = "DojoModel"
class_hash = "0x44ed04ed95bba5a2912891479784149c37e61082b8f8ea1fea1777e9b67f486"
name = "nogame::colony::models::colony_ships"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "colony_id"
type = "u8"
key = true

[[members]]
name = "name"
type = "u8"
key = true

[[members]]
name = "count"
type = "u32"
key = false
