kind = "DojoModel"
class_hash = "0x7334e31c89269a9b637b674dcb87b9b8462ffb4c94a407816d5bd099a54a4f3"
name = "nogame::colony::models::colony_owner"

[[members]]
name = "colony_planet_id"
type = "u32"
key = true

[[members]]
name = "planet_id"
type = "u32"
key = false
