kind = "DojoModel"
class_hash = "0x6887eea56dcae2f8afb667b84707516e4624e970786d66963fca0d5f6fef141"
name = "nogame::game::models::game_planet"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "planet_id"
type = "u32"
key = false
