kind = "DojoModel"
class_hash = "0x723f16e88f7f2634a90999d4573983e2bf793387948c876155c4789dddf9c5d"
name = "nogame::fleet::models::incoming_mission_len"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "lenght"
type = "usize"
key = false
