kind = "DojoModel"
class_hash = "0x62163e3fefc1f2d48707b6cc23ce8e469fc78823bd06c0be036c85ad5a227c3"
name = "nogame::planet::models::last_active"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "time"
type = "u64"
key = false
