kind = "DojoModel"
class_hash = "0x30e0a1bacfe8c773aa479da784bc4452e6a3a3221e17a5d2f7bc7a9e12f944e"
name = "nogame::planet::models::planet_resources_spent"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "spent"
type = "u128"
key = false
