kind = "DojoModel"
class_hash = "0x3d27045397690562c4bacf11a1b65d37c9737c73f552a91e3b1c03347582b88"
name = "nogame::tech::models::planet_techs"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "name"
type = "u8"
key = true

[[members]]
name = "level"
type = "u8"
key = false
