kind = "DojoModel"
class_hash = "0x6a181f1fe73501f37ad7c0ae0a8f8cc4e7850699047ec1931702eb94e085824"
name = "nogame::planet::models::planet_resource_timer"

[[members]]
name = "planet_id"
type = "u32"
key = true

[[members]]
name = "last_collection"
type = "u64"
key = false
